### ISSUE TITLE
Questions re: `[class*="m-"]` and @60 media query

### ISSUE THREAD

**Issue by C-G-G** [C-G-G/registration-form#1]
I have two questions re: Markbot's expectations to see `[class*="m-"]` and @60 media query:

1- I used only `unit-xs` and `unit-l` (because layout changes @60em), and am not sure why we would need to use `unit-m` (nothing is expected to change in layout at medium screen if I'm not mistaken)?

2- I guess the only thing I need to do @60 media query is to take care of the divs (fields) that line up next to each other. I thought about using gutter or giving a width to put space between fields but then there is also that strange behaviour of the Age div (screenshot attached). 

While here, may I also ask the best way to center the register button (nothing worked so far) and where we are expected to use paddings 1rem and .5rem (button?) ? 

Thanks!  

@thomasjbradley

<img width="993" alt="Screen Shot 2021-08-23 at 9 44 08 PM" src="https://user-images.githubusercontent.com/16348315/130543040-8771feec-abbf-4dc5-9ece-898c90690c7a.png">

**Comment by thomasjbradley** [comment]
> 1- I used only unit-xs and unit-l (because layout changes @60em), and am not sure why we would need to use unit-m

I like to avoid skipping sizes going up. So, because a `l` size was used I want to see all the sizes below that defined too.
I kinda parallels how the media queries are written.

> Centre button:

Remove `.unit` from the `<div>` & add `text-center`.

> Aligning fields:

- There’s a `pad-t` on the name field that you can remove.
- For the space between the fields, I added classes to their divs & just padded them manually
- If we weren’t using such a strict grid we could use `gap` to do it for us.

![Screen Shot 2021-09-02 at 8 05 53 PM](https://user-images.githubusercontent.com/105192/131931088-bf66c5d6-816e-4c32-977c-3c93f558f5f9.png)

> `1rem`
Used to push the legend’s border away from the text

> `.5rem`
The spacing between the inputs.

**Comment by C-G-G** [comment]
Thanks so much! All good except the spacing between the inputs: 

Not sure if I got it right but added padding-right to divs (Name and Email) and padding-left to other two divs (Age and Physical fitness). Now Markbot's screenshots don't match (fields are not even on same line in my screenshot although they look fine in browser). May I ask how you put spacing between the inputs @60em?

<img width="963" alt="Screen Shot 2021-09-03 at 12 04 53 PM" src="https://user-images.githubusercontent.com/16348315/132036100-95437240-a7cf-428d-a397-183c1a725c03.png">

<img width="612" alt="Screen Shot 2021-09-03 at 12 07 06 PM" src="https://user-images.githubusercontent.com/16348315/132036142-85a60c74-1cdf-4eed-9441-a6495c6cf87b.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
I wonder if it has got to do with where `.grid` is. I have it *not* on the `<form>` but on a `<div>` *inside* the form, starting after the `<legend>`.
